-- phpMyAdmin SQL Dump
-- version 4.1.12
-- http://www.phpmyadmin.net
--
-- Servidor: localhost:8889
-- Tiempo de generación: 06-08-2014 a las 19:27:48
-- Versión del servidor: 5.5.34
-- Versión de PHP: 5.5.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `prueba`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `CAT_PREGUNTAS`
--

CREATE TABLE `CAT_PREGUNTAS` (
  `id_pregunta` int(11) NOT NULL AUTO_INCREMENT,
  `id_version` int(11) DEFAULT NULL,
  `id_modulo` int(11) DEFAULT NULL,
  `id_subModulo` int(11) DEFAULT NULL,
  `numPregunta` varchar(10) DEFAULT NULL,
  `pregunta` longtext,
  `recomendacion` longtext,
  `valor` int(11) DEFAULT NULL,
  `orden` int(11) DEFAULT NULL,
  `id_estructuraDiag` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_pregunta`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=163 ;

--
-- Volcado de datos para la tabla `CAT_PREGUNTAS`
--

INSERT INTO `CAT_PREGUNTAS` (`id_pregunta`, `id_version`, `id_modulo`, `id_subModulo`, `numPregunta`, `pregunta`, `recomendacion`, `valor`, `orden`, `id_estructuraDiag`) VALUES
(1, 2, 17, NULL, '1', 'Â¿La empresa agrÃ­cola y todas las unidades que la integran estÃ¡n registradas y vigente en la pÃ¡gina web del SENASICA y se cuenta con copia impresa?', 'Las empresa agrÃ­cola y las Unidades Productivas que la integran deben estar registradas y vigentes en la pÃ¡gina ElectrÃ³nica del SENASICA. AdemÃ¡s se debe contar con una copia impresa de la constancia de inscripciÃ³n emitida por la pÃ¡gina ElectrÃ³nica la cual deberÃ¡ contener el nÃºmero de identificaciÃ³n asignado a la empresa asÃ­ como los datos de cada Unidad Productiva registrada.', 10, 1, 1),
(2, 2, 17, NULL, '2', 'Â¿Se  utiliza  para  la  identificaciÃ³n  del  manual  de operaciones?', 'El nÃºmero de identificaciÃ³n asignado debe utilizarse de la misma forma para la identificaciÃ³n del manual de operaciones.', 10, 2, 1),
(3, 2, 18, 332, '4', 'Â¿La localizaciÃ³n de las instalaciones se definiÃ³ en base a un anÃ¡lisis de peligros previo a las  necesidades de la empresa?', 'El Profesional en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n de  la  empresa,  debe  definir  las  necesidades  de instalaciones y la localizaciÃ³n de Ã©stas en base a un anÃ¡lisis de peligros.', 10, 1, 1),
(4, 2, 18, 332, '5', 'Â¿Se cuenta con un plano de localizaciÃ³n y un croquis de ubicaciÃ³n de las instalaciones correctamente identificadas?', 'Debe generarse un plano de instalaciones que identifique la localizaciÃ³n de las instalaciones en la empresa o el Ã¡rea. Este debe indicar la ubicaciÃ³n exacta de la instalaciÃ³n y su relaciÃ³n con fuentes de agua,Ã¡reas productivas, casas, Ã¡rea de almacenamiento de agroquÃ­micos, entre otras.', 10, 2, 1),
(5, 2, 18, 333, '6', 'Â¿Se han valorado los factores de riesgo que pueden introducir un contaminante de origen biolÃ³gico y quÃ­mico a la unidad de empaque, asÃ­ como el tipo de barrera fÃ­sica que reduzca las posibilidades ingreso al empaque?', 'El profesional en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n, debe definir el tipo de barrera fÃ­sica que debe aplicarse en la Unidad Productiva. La barrera fÃ­sica debe tener la capacidad de impedir el ingreso de animales domÃ©sticos y silvestres del exterior, escurrimientos, personas ajenas a la Unidad Productiva u otros factores de riesgo identificados que puedan posicionar o introducir un contaminante de origen biolÃ³gico y quÃ­mico a la Unidad Productiva, a  las  fuentes  de  agua,  Ã¡reas  de empacado.', 10, 1, 1),
(6, 2, 18, 333, '7', 'Â¿Se supervisa de manera periÃ³dica que la barrera de protecciÃ³n se mantiene en buen estado fÃ­sico y se registra esta actividad?', 'El responsable debe asegurarse y demostrar que la barrera de protecciÃ³n se mantiene en buen estado fÃ­sico y que asegura la eficacia para lo que fue generada.', 10, 2, 1),
(7, 2, 18, 334, '8', 'Â¿Se valora a travÃ©s de un anÃ¡lisis de peligros la ubicaciÃ³n mÃ¡s adecuada para instalar las estaciones sanitarias, asÃ­ como prevenir la contaminaciÃ³n de fuentes de agua, almacenamiento, empaque de productos, personas y otros factores que por contacto directo o indirecto puedan contaminar los productos?', 'El Profesional en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe valorar a travÃ©s de un anÃ¡lisis de peligros la ubicaciÃ³n mÃ¡s adecuada donde se instalaran las Estaciones Sanitarias. La ValoraciÃ³n debe orientarse hacia la evaluaciÃ³n del riesgo (derrames, deficiencias en su construcciÃ³n, materia fecal y bio sÃ³lidos), que la ubicaciÃ³n, de este tipo de instalaciones pueda posicionarse o introducir un contaminante de tipo biolÃ³gico y/o quÃ­mico hacia las fuentes de agua, Ã¡rea productiva, Ã¡reas de empacado, almacenamiento de producto y/o personas por contacto directo o indirecto.', 10, 1, 1),
(8, 2, 18, 344, '9', 'Â¿Se cuenta con una persona responsable del sistema de reducciÃ³n de riesgos que demuestre su conocimiento en dicha Ã¡rea?', 'La empresa debe contar con una persona responsable de la aplicaciÃ³n y vigilancia del Sistema de ReducciÃ³n de Riesgos de ContaminaciÃ³n de su empresa. Esta persona debe demostrar conocimiento en las prÃ¡cticas preventivas aplicadas. La empresa debe contar con la asesorÃ­a de un profesional en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n que demuestre la competencia tÃ©cnica suficiente para diseÃ±ar, implementar y evaluar el Sistema en productos de origen agrÃ­cola acorde a las condiciones productivas y en concordancia con las disposiciones oficiales.', 10, 1, 1),
(9, 2, 18, 344, '10', 'Â¿Se demuestra que todos los trabajadores estÃ¡n involucrados en el cumplimiento de las acciones preventivas y/o correctivas y que existen responsabilidades bien definidas?', 'El responsable debe apoyarse con coordinadores de equipo, cuando asÃ­ se justifique, los cuales le apoyaran en la verificaciÃ³n del cumplimiento y registro de las medidas de control aplicadas por la empresa.  Ejemplo:  responsable de  la limpieza y desinfecciÃ³n, transporte, Ã¡rea de cuarto frÃ­o,  del  Ã¡rea  de empacado, etc.', 10, 2, 1),
(10, 2, 18, 344, '11', 'Â¿Se tiene un organigrama y  un perfil de puestos?', 'La empresa debe demostrar mediante un organigrama y un perfil de puestos y funciones el nombre de las personas que asesoran, coordinan, verifican, y evalÃºan el Sistema de ReducciÃ³n de Riesgos de ContaminaciÃ³n, asÃ­ como las funciones y acciones puntuales que cada uno de los involucrados desarrolla.', 10, 3, 1),
(11, 2, 18, 345, '12', 'Â¿Se cuenta con un expediente tÃ©cnico conformado por evidencias suficientes y pertinentes que demuestren que las acciones se aplican cotidianamente y que Ã©stas son eficaces, asÃ­ como un expediente tÃ©cnico que refleje el ciclo actual de operaciones?', 'La empresa debe presentar un expediente tÃ©cnico integrado por evidencias documentales suficientes y pertinentes que demuestren que las acciones se aplican cotidianamente y que son eficaces. El expediente  tÃ©cnico  debe  reflejar  el  ciclo  actual  de  operaciones (ligado al ciclo actual de cultivo).', 10, 1, 1),
(12, 2, 18, 345, '13', 'Â¿Los documentos  y  registros son originales sustentados con documentos de apoyo,  con  firma  autÃ³grafa,  sin  tachaduras  y/o enmendaduras, en su caso Ã©stas estÃ¡n validadas, reflejan el Ãºltimo aÃ±o de operaciones y se encuentra resguardado por la empresa?', 'Debe contener documentos originales con firma autÃ³grafa. Tachaduras  y/o  enmendaduras debidamente validadas  por  el responsable de la empresa.', 10, 2, 1),
(13, 2, 18, 345, '14', 'Â¿El expediente tÃ©cnico estÃ¡ estructurado por mÃ³dulos de ejecuciÃ³n conteniendo el anÃ¡lisis de peligros, el plan tÃ©cnico derivado, los procedimientos que se aplican en ese mÃ³dulo, los registros generados, los documentos suficientes y pertinentes que demuestren la eficacia de los tratamientos aplicados y la veracidad de los registros?', 'El expediente tÃ©cnico debe estar estructurado por mÃ³dulos de ejecuciÃ³n debiendo contener en cada secciÃ³n:\r\na) El anÃ¡lisis de peligros.\r\nb) El plan tÃ©cnico derivado.\r\nc) Los procedimientos que se aplican en ese modulo.\r\nd) registros generados.\r\ne) Documentos y registros que demuestren la eficacia de los tratamientos aplicados y la veracidad de los registros.', 10, 3, 1),
(14, 2, 18, 345, '15', 'Â¿Los procedimientos son congruentes con el plan tÃ©cnico, originales sin logos ajenos a la empresa y con periodo de revisiÃ³n definido no superior a un aÃ±o?', 'Los procedimientos deber ser congruentes con el plan tÃ©cnico. Originales y con periodos de revisiÃ³n definidos no superiores a un aÃ±o. No debe contener logos ajenos a la empresa.', 10, 4, 1),
(15, 2, 18, 345, '16', 'Â¿Cuentan los procedimientos con los siguientes elementos: Describen las acciones puntuales a realizarse, seÃ±ala al responsable de su ejecuciÃ³n, seÃ±alan los indicadores para su evaluaciÃ³n, cuentan con la firma autÃ³grafa de representante legal y/o responsable del SRRC, asÃ­ como el nombre de la empresa, alcance y cultivos?', 'Los procedimientos deberÃ¡n describir las acciones puntuales a realizarse y el responsable de su ejecuciÃ³n, tener la firma autÃ³grafa por el represente legal y responsable del Sistema de ReducciÃ³n de Riesgos de ContaminaciÃ³n e indicar el nombre de la empresa, alcance, cultivos y superficies.', 10, 5, 1),
(16, 2, 18, 345, '17', 'Â¿La  empresa  genera  registros  suficientes  y  pertinentes  que  demuestren  el cumplimiento de las acciones previstas en los procedimientos?', 'Las empresas deben generar los registros y bitÃ¡coras suficientes y pertinentes que demuestren el cumplimiento y la eficacia de los tratamientos descritos en los procedimientos. Tales registros deben resaltar los indicadores que pretenden demostrarse en papel o electrÃ³nicos. Deben incluir la caracterÃ­stica evaluada, el hecho (Dato), la fecha  en  que  se  realiza,  el  responsable,  la  unidad  de medida, grÃ¡ficos de control, tablas o listas de verificaciÃ³n.', 10, 6, 1),
(17, 2, 18, 345, '18', 'Â¿Los procedimientos y registros estÃ¡n integrados mediante un listado maestro y en el cual indica su vigencia?', 'Los procedimientos y registros deben integrase mediante un listado maestro y en el cual deberÃ¡ indiciar su vigencia.', 10, 7, 1),
(18, 2, 19, 346, '23', 'Â¿Se aplica un plan de higiene a la totalidad de las instalaciones existentes en la unidad productiva acorde al procedimiento, frecuencia y tratamiento previsto?', 'DeberÃ¡ aplicar un plan de higiene a la totalidad de las instalaciones existentes en la Unidad Productiva acorde al procedimiento, frecuencia y tratamiento previstos.', 10, 1, 1),
(19, 2, 19, 346, '24', 'Â¿Se mantienen las instalaciones limpias, durante el proceso productivo y se limpian al menos una vez al mes durante el periodo en que no se encuentran en fase productiva?', 'Las instalaciones deben mantenerse limpias durante el proceso productivo y limpiarse al menos una vez al mes durante el periodo en que no se encuentre en fase productiva.', 5, 2, 1),
(20, 2, 19, 347, '25', 'Â¿La Empresa cuenta con un procedimiento documentado que describa las acciones que se aplican para garantizar la higiene de los trabajadores y Ã©ste se encuentra en concordancia con lo dispuesto en la secciÃ³n 5 de la NOM-251-SSA1?', 'Deben elaborar un procedimiento documentado que describa las acciones que se aplican para garantizar la higiene de los trabajadores y que Ã©ste se encuentre en concordancia segÃºn lo dispuesto en la secciÃ³n 5, disposiciones para el personal de la NOM-120-SSA1-1994 o NOM-251-SSA1.', 10, 1, 1),
(21, 2, 19, 347, '26', 'Â¿Cuentan con  evidencias (registros) que  demuestren el  cumplimiento de  las prÃ¡cticas de higiene durante el manejo y empacado del alimento de origen vegetal acordes al plan de higiene generado por la empresa?', 'Debe generar evidencias (registros) que demuestren el cumplimiento de las prÃ¡cticas de higiene durante el manejo  y empacado del alimento de origen agrÃ­cola y acordes al plan de higiene generado por la empresa.', 10, 2, 1),
(22, 2, 19, 348, '27', 'Â¿Las herramientas y equipos de trabajo se lavan y desinfectan de acuerdo a la frecuencia definida en el plan de higiene?', 'Todas  las  herramientas  y  equipos  de  trabajo  deben  lavarse  y desinfectarse acorde a la frecuencia definida en el plan de higiene.', 10, 1, 1),
(23, 2, 19, 348, '28', 'Â¿La unidad de empaque se mantiene libre de basura, residuos de cosecha, piedras amontonadas, materiales en desuso, residuos, recipientes, contenedores de lÃ­quidos y todo aquello que pueda constituir una fuente de contaminaciÃ³n y se revisa semanalmente?', 'El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe revisar de acuerdo con la frecuencia establecida en el plan tÃ©cnico, la Unidad Empaque y debe asegurarse que Ã©sta se mantiene limpia y libre de basura.', 5, 2, 1),
(24, 2, 18, 356, '3', 'Â¿En caso de que varias secciones de empaque compartan instalaciones, documentos y personas se demuestra que pertenecen a la misma empresa, que el producto se genera bajo condiciones productivas similares y estÃ¡ tÃ©cnicamente justificado y sustentado?', 'La infraestructura aplicada debe ser por empresa o por Ã¡rea. Esto implica que Unidades Productivas y Ã¡reas podrÃ¡n compartir instalaciones, documentos y personas. Siempre y cuando demuestren que pertenecen a la misma empresa o Ã¡rea integral. Ã‰sta debe estar tÃ©cnicamente justificada y sustentada mediante un ejercicio de anÃ¡lisis de peligros que valore su ubicaciÃ³n y su construcciÃ³n.', 10, 1, 1),
(25, 2, 19, 357, '19', 'Â¿Se cuenta con una anÃ¡lisis de peligro y un plan tÃ©cnico integrado  por procedimientos operativos estandarizados, registros  y documentos generados, evidencias que demuestren que las acciones aplicadas son eficaces, anÃ¡lisis microbiolÃ³gicos de superficies de contacto vivas y no vivas, que tengan contacto directo con producto, plan de capacitaciÃ³n y reforzamiento de la informaciÃ³n al personal involucrado en esta materia?', 'El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe elaborar un  plan tÃ©cnico de higiene basado en un anÃ¡lisis de peligros de la empresa para: Unidades Productivas y/o empaque, Trabajadores, Instalaciones, Maquinaria, Herramienta y Equipos de trabajo.\r\nEl plan de higiene debe estar integrado por:\r\nA)  AnÃ¡lisis de peligros.          \r\nB)  Procedimientos Operativos Estandarizados.\r\nC)  Registros y documentos generados.\r\nD)  Evidencias que demuestren que las acciones aplicadas son eficaces, anÃ¡lisis microbiolÃ³gicos de superficies de contacto vivas y no vivas que tengan contacto directo con producto.\r\nE)  Plan de CapacitaciÃ³n y reforzamiento de la informaciÃ³n al personal involucrado en esta materia.', 10, 1, 1),
(26, 2, 19, 357, '20', 'Â¿Cuenta la empresa con procedimientos para la preparaciÃ³n de sustancias desinfectantes que aplican en el programa de higiene?', 'El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe elaborar procedimientos para la preparaciÃ³n de Sustancias desinfectantes que aplican en el programa de higiene.', 10, 2, 1),
(27, 2, 19, 357, '21', 'Â¿Se garantiza que la concentraciÃ³n deseada se mantiene durante el tiempo requerido para su acciÃ³n desinfectante asÃ­ como la reducciÃ³n de la presencia del contaminante valorado?', 'El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe asegurarse que la concentraciÃ³n deseada se mantiene durante el tiempo requerido para su acciÃ³n desinfectante asÃ­ como que Ã©sta reduce la presencia del contaminante valorado.', 5, 3, 1),
(28, 2, 19, 357, '22', 'Â¿Se demuestra que los tratamientos aplicados reducen la carga microbiana de las superficies y sustancias sobre las cuales son utilizados?', 'DeberÃ¡n demostrar que los tratamientos aplicados reducen la carga microbiana de las superficies y sustancias sobre las cuales sean utilizadas.', 10, 4, 1),
(29, 2, 222, NULL, '29', 'Â¿Se cuenta con una anÃ¡lisis de peligro y un plan tÃ©cnico integrado  por procedimientos operativos estandarizados, registros  y documentos generados, evidencias que demuestren que las acciones aplicadas son eficaces?', 'La empresa debe realizar una valoraciÃ³n del riesgo de contaminaciÃ³n asociado a la presencia de animales domÃ©sticos y silvestres en las Unidades de Empaque y definir las medidas apropiadas para prevenirlo.', 10, 1, 1),
(30, 2, 222, NULL, '30', 'Â¿En caso de que se utilice el tratamiento con agentes quÃ­micos y biolÃ³gicos, Ã©stos se han aplicado bajo la supervisiÃ³n directa de personal que conozca los riesgos para la salud, que el uso de esos agentes puede entraÃ±ar?', 'En caso de que alguna especie animal ingrese el establecimiento, deben adoptarse medidas de control o erradicaciÃ³n. Las medidas que comprendan el tratamiento con agentes quÃ­micos y biolÃ³gicos, sÃ³lo deben aplicarse bajo la supervisiÃ³n directa del personal que conozca a fondo los riesgos para la salud, que el uso de esos agentes puede ocasionar.', 10, 2, 1),
(31, 2, 222, NULL, '31', 'Â¿Se cuenta con mapas de localizaciÃ³n de las trampas para plagas en el exterior e interior de la unidad empaque, las cuales deben estar plenamente identificadas?', 'Se debe contar con mapas de localizaciÃ³n de trampas para plagas en el exterior e interior de la Unidad de Empaque. Las trampas colocadas en el exterior deben estar plenamente identificadas y crear un cerco perimetral. En estas trampas se pueden utilizar cebos o rodenticidas quÃ­micos para controlar roedores.', 10, 3, 1),
(32, 2, 20, NULL, '32', 'Â¿Se cuenta con una anÃ¡lisis de peligro y un plan tÃ©cnico integrado  por un procedimiento de capacitaciÃ³n, que especifique la metodologÃ­a, la frecuencia, los instrumentos, el lugar y las personas a quien va dirigido cada tema asÃ­ como registros  y documentos generados?', 'Las Unidades de Empaque o Ã¡reas con aplicaciÃ³n de Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n deben contar con un anÃ¡lisis de peligros y un plan tÃ©cnico integrado por registros y procedimientos de capacitaciÃ³n, que especifique la metodologÃ­a, la frecuencia, los instrumentos, el lugar y las personas a quien va dirigido cada tema.', 10, 1, 1),
(33, 2, 20, NULL, '33', 'Â¿Se demuestra la capacitaciÃ³n a empleados permanentes y eventuales, al inicio, durante la temporada, cada vez que ingresa personal y cuando se realizan cambios en los procedimientos?', 'Se debe capacitar a empleados permanentes y eventuales, al inicio, durante la temporada, cada vez que ingrese personal y cuando se realicen cambios en los procedimientos.', 5, 2, 1),
(34, 2, 20, NULL, '34', 'Â¿El capacitador se apoya en material grÃ¡fico del tema expuesto para lectura, asÃ­ como uso de un rotafolio y manuales, cuando asÃ­ aplica y se realizan demostraciones tÃ©cnicas y prÃ¡cticas para que el trabajador las aplique?', 'El capacitador se debe apoyar en material grÃ¡fico del tema expuesto para lectura (dÃ­ptico, trÃ­ptico, folleto, etc.), asÃ­ como hacer uso de un rotafolio, material grÃ¡fico y manuales, cuando aplique.\r\nSe deben realizar demostraciones tÃ©cnicas y prÃ¡cticas necesarias para que el trabajador las aplique.', 10, 3, 1),
(35, 2, 20, NULL, '35', 'Â¿Se  demuestra  el  conocimiento  del  capacitador,  mediante  soporte  documental  de  una instituciÃ³n u organismo reconocido por su competencia tÃ©cnica en el tema?', 'El capacitador debe demostrar su conocimiento mediante soporte documental de una instituciÃ³n u organismo reconocido por su competencia tÃ©cnica en el tema.', 10, 4, 1),
(36, 2, 20, NULL, '36', 'Â¿El supervisor y responsable de inocuidad de Empresa, demuestra su competencia en BPAs y BPMs que haya sido impartida por el SENASICA y/o por sus organismos auxiliares?', 'El supervisor y responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n de Unidad de Empaque y Ã¡reas con aplicaciÃ³n de  Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe demostrar su competencia en BPAs y BPMs reconocida por el SENASICA.', 10, 5, 1),
(37, 2, 21, NULL, '38', 'Â¿Se ha realizado una evaluaciÃ³n anual del Sistema de ReducciÃ³n de Riesgos de ContaminaciÃ³n aplicado en el o los empaques, que conforman la empresa o bien al menos dos evaluaciones cuando Ã©stas se han dirigido hacia un modulo especifico?', 'Las empresas deben aplicar de manera obligada una evaluaciÃ³n anual del Sistema de ReducciÃ³n de Riesgos de ContaminaciÃ³n aplicado en las Unidades Productivas que la conforman o bien al menos dos evaluaciones cuando Ã©stas se dirigen hacia un mÃ³dulo especifico.', 10, 1, 1),
(38, 2, 21, NULL, '39', 'Â¿La evaluaciÃ³n del  sistema de ReducciÃ³n de Riesgos, estÃ¡ descrita en un procedimiento documentado que  especifique la  metodologÃ­a, frecuencia, criterios de  auditorÃ­a, tipo  de evidencia y acciones correctivas a aplicarse?', 'La   evaluaciÃ³n   del   Sistema   de   ReducciÃ³n   de   Riesgos  de contaminaciÃ³n deberÃ¡ estar descrita en un procedimiento documentado donde especifique la metodologÃ­a, frecuencia, criterios de auditorÃ­a, tipo de evidencia y acciones correctivas a aplicarse.', 10, 2, 1),
(39, 2, 21, NULL, '40', 'Â¿El responsable de realizar  la evaluaciÃ³n interna, demuestra su competencia en evaluaciÃ³n de Sistemas de ReducciÃ³n de Riesgos?', 'El responsable de la evaluaciÃ³n interna debe demostrar su competencia  en  el  tema  de  evaluaciÃ³n  de  Sistemas  de ReducciÃ³n de Riesgos de ContaminaciÃ³n.', 10, 3, 1),
(40, 2, 21, NULL, '41', 'Â¿El proceso de evaluaciÃ³n se realiza tomando como referencia la lista de verificaciÃ³n sugerida por SENASICA?', 'El proceso de evaluaciÃ³n podrÃ¡ tomar como referencia lo sugerido por el SENASICA a travÃ©s del instrumento publicado para tal efecto.', 10, 4, 1),
(41, 2, 22, NULL, '42', 'Â¿La empresa demuestra, mediante la generaciÃ³n de informaciÃ³n suficiente y pertinente que los tratamientos aplicados en Ã¡reas crÃ­ticas son eficaces en la prevenciÃ³n, reducciÃ³n y/o eliminaciÃ³n de contaminantes de tipo biolÃ³gico y quÃ­mico que puedan ser daÃ±inos a la salud humana?', 'Las empresas deben demostrar mediante la generaciÃ³n de informaciÃ³n suficiente y pertinente que los tratamientos aplicados en Ã¡reas crÃ­ticas son eficaces en la prevenciÃ³n, reducciÃ³n y/o eliminaciÃ³n  de  contaminantes  de  tipo  biolÃ³gico  y  quÃ­mico  que puedan ser daÃ±inos a la salud humana.', 10, 1, 1),
(42, 2, 22, NULL, '43', 'Â¿El Sistema de ValidaciÃ³n de Procedimientos estÃ¡ descrito en un procedimiento documentado, que indique los puntos crÃ­ticos, periodos, metodologÃ­as aplicadas e indicadores que serÃ¡n aplicados para evaluar la eficacia de los tratamientos?', 'El Sistema de ValidaciÃ³n de Procedimientos deberÃ¡ estar  descrito  en  un  procedimiento  documentado,  que indique los puntos crÃ­ticos, periodos, metodologÃ­as aplicadas e indicadores que serÃ¡n aplicados para evaluar la eficacia de los tratamientos.', 10, 2, 1),
(43, 2, 22, NULL, '44', 'Â¿Se han generado registros de la validaciÃ³n de los procedimientos realizados?', 'La empresa debe generar registros de la validaciÃ³n de los procedimientos realizados.', 10, 3, 1),
(44, 2, 22, NULL, '45', 'Â¿La validaciÃ³n se ha realizado en Laboratorios de MicrobiologÃ­a de Centros de InvestigaciÃ³n, de EnseÃ±anza superior o Laboratorios Estatales de Salud Publica?', 'Esta deberÃ¡ realizarse por Laboratorios de MicrobiologÃ­a de Centros de InvestigaciÃ³n, de EnseÃ±anza Superior o Laboratorios Estatales de Salud Publica de la entidad federativa donde se localiza la empresa.', 10, 4, 1),
(45, 2, 22, NULL, '46', 'Â¿Los procedimientos considerados como crÃ­ticos se han evaluado al menos una vez por ciclo productivo?', 'Los procedimientos considerados como crÃ­ticos deberÃ¡n ser evaluados al menos una vez por ciclo.', 10, 5, 1),
(46, 2, 22, NULL, '47', 'Â¿Una vez se han aplicado las acciones de higiene y desinfecciÃ³n descritas en el Procedimiento de superficie de contacto no vivas, se ha demostrado ausencia de Coliformes fecales, Salmonella spp y Escherichia coli, y en caso contrario se ha identificado el serovar especÃ­fico del cual se trate?', 'Las superficies de contacto no vivas (Mesas de empaque, bandas, bancos, paredes interiores de depÃ³sitos de agua para consumo humano, como mÃ­nimo), una vez que estas han aplicado las acciones de higiene y desinfecciÃ³n descritas en el procedimiento correspondiente. Estos deberÃ¡n demostrar ausencia de Coliformes fecales, Salmonella spp y Escherichia coli.   DeberÃ¡ identificar el serovar especÃ­fico del cual se trate.', 10, 6, 1),
(47, 2, 22, NULL, '48', 'Para el caso de manos de trabajadores, despuÃ©s de haberse higienizado, se ha demostrado la ausencia de Coliformes fecales, Salmonella spp y Escherichia coli?', 'Las manos de trabajadores, despuÃ©s de haberse higienizado durante la etapa de empacado y transporte. Los indicadores a evaluar serÃ¡n los siguientes: Coliformes fecales, Salmonella spp y Escherichia coli que deberÃ¡n estar ausentes despuÃ©s la higienizaciÃ³n.', 10, 7, 1),
(48, 2, 22, NULL, '49', 'Â¿Para el caso de que se haya aplicado algÃºn tratamiento preventivo en el agua de manejo y consumo descrito en el procedimiento correspondiente, se ha demostrado la ausencia de los indicadores de contaminaciÃ³n previstos en la NOM-127-SSA1-1994?', 'El agua  para uso  y  consumo  humano a las que se les haya aplicado un tratamiento preventivo descrito en el procedimiento correspondiente. Los resultados deberÃ¡n demostrar la ausencia de los indicadores de contaminaciÃ³n previstos en la NOM-127-SSA1-1994.', 10, 8, 1),
(49, 2, 22, NULL, '50', 'Â¿Se demuestra que el tiempo de contacto, temperatura, ruptura fÃ­sica de la suciedad y la calidad quÃ­mica del agua son adecuados para la efectividad del detergente elegido?', 'DeberÃ¡n demostrar que los tratamientos aplicados reducen la carga microbiana de las superficies y sustancias sobre las cuales sean utilizadas.\r\nLos detergentes y desinfectantes deben ser seleccionados cuidadosamente para lograr el fin perseguido. No deben contener aromatizantes y su alcalinidad o acidez dependerÃ¡ de la superficie a higienizar. Los residuos de estos agentes que queden en una superficie susceptible de entrar en contacto con los productos, deben eliminarse mediante un enjuague minucioso con agua potable.', 10, 9, 1),
(50, 2, 22, NULL, '51', 'Â¿Se demuestra la ausencia de molÃ©culas no autorizadas en nuestro paÃ­s y/o mercado destino y el cumplimiento de los LMR de productos utilizados, asÃ­ como la ausencia de organismos patÃ³genos como Salmonella spp y Escherichia coli?', 'Los frutos durante la fase de cosecha, sobre los cuales se deberÃ¡ demostrar la ausencia de molÃ©culas no autorizadas en nuestro paÃ­s y/o mercado destino, cumplimiento de los LMR de productos autorizados para su uso asÃ­ como evaluar la presencia de organismos patÃ³genos como Salmonella spp y Escherichia coli.', 10, 10, 1),
(51, 2, 22, NULL, '52', 'Â¿La metodologÃ­a aplicada es  la descrita en las normas oficiales aplicables vigentes de  la Secretaria de Salud?', 'La metodologÃ­a a aplicarse serÃ¡ la descrita por las normas oficiales aplicables vigentes de la Secretaria de Salud.', 10, 11, 1),
(52, 2, 22, NULL, '53', 'Â¿La empresa se asesora con el prestador de servicio de validaciÃ³n, para determinar el tamaÃ±o de muestras a recabar por cada evaluaciÃ³n a realizar?', 'La empresa deberÃ¡ asesorarse con el prestador de servicios de validaciÃ³n para determinar el tamaÃ±o de muestra a recabar por cada evaluaciÃ³n a realizar.', 10, 12, 1),
(53, 2, 23, NULL, '54', 'Â¿Se ha elaborado un procedimiento documentado que describa el sistema de trazabilidad aplicado por la empresa que identifique con claridad la trazabilidad hacia atrÃ¡s, la trazabilidad interna y la trazabilidad hacia adelante con respecto a la empresa?', 'Debe elaborarse un procedimiento documentado que describa el sistema de trazabilidad aplicado por la empresa.\r\nEl sistema debe identificar con claridad la trazabilidad hacia atrÃ¡s, la trazabilidad interna y la trazabilidad hacia adelante con respecto a la empresa.', 10, 1, 1),
(54, 2, 23, NULL, '55', 'Â¿El cÃ³digo generado indica con claridad el Estado, municipio y un nÃºmero consecutivo de identificaciÃ³n de la unidad, integrado por al menos 6 (seis) dÃ­gitos?', 'El cÃ³digo generado debe indicar con claridad el Estado, municipio y un nÃºmero consecutivo de identificaciÃ³n de la Unidad. El cÃ³digo deberÃ¡ integrarse por al menos 6 (seis) dÃ­gitos. Para cultivos que son regulados fitosanitariamente podrÃ¡ utilizarse el nÃºmero de identificaciÃ³n asignado por la DirecciÃ³n General de Sanidad Vegetal.', 10, 2, 1),
(55, 2, 23, NULL, '56', 'Â¿La trazabilidad hacia atrÃ¡s identifica a los proveedores de los insumos que se requieren para la producciÃ³n, cosecha y empaque del producto?', 'La trazabilidad hacia atrÃ¡s debe cumplir con los requisitos siguientes: A) Identificar a los proveedores de los insumos que se requieren para la producciÃ³n, cosecha y empacado del producto.', 10, 3, 1),
(56, 2, 23, NULL, '57', 'Â¿Se han generado registros documentados de los insumos que la empresa adquiere para las unidades de empaque?', 'B) Generar  registros  documentados  de  los  insumos  que  la empresa adquiere para las Unidades Productivas. El registro debe  indicar  la  informaciÃ³n  siguiente:  Fecha,  nombre  del proveedor, numero  de  certificaciÃ³n  SENASICA (Proveedor), Nombre comercial del producto, nombre tÃ©cnico, ingrediente activo, formulaciÃ³n, presentaciÃ³n, lote, nÃºmero de registro oficial emitido por la autoridad competente, volumen adquirido y responsable de la recepciÃ³n.', 10, 4, 1),
(57, 2, 23, NULL, '58', 'Â¿Se cuenta con un directorio actualizado de proveedores de servicios que incluya nombre de la empresa, localizaciÃ³n, telÃ©fono, direcciÃ³n electrÃ³nica?', 'C) DeberÃ¡ contar con un directorio actualizado de proveedores de servicios que incluya el nombre de la empresa, localizaciÃ³n, telÃ©fono, direcciÃ³n electrÃ³nica.', 10, 5, 1),
(58, 2, 23, NULL, '59', 'Â¿Se han registrado como mÃ­nimo los insumos: productos y sustancias quÃ­micas desinfectantes, agua, tarimas, cajas, flejes, ceras, aceites, lubricantes y todos aquellos que tienen un contacto directo con el producto?', 'D) Los insumos mÃ­nimos que deben ser registrados son los siguientes: productos y sustancias agroquÃ­micas como plaguicidas, fertilizantes, desinfectantes, sustratos, acolchados, agua, tarimas, cajas, flejes, grasas, ceras, aceites, lubricantes y todos aquellos que tengan un contacto directo con el producto.', 10, 6, 1),
(59, 2, 23, NULL, '60', 'Â¿Se han identificado a los prestadores de servicio como asesores, empresas de limpieza, empresas de control de plagas urbanas?', 'E) De la misma forma deben identificarse a los prestadores de servicio como asesores, cuadrillas de corte, empresas de limpieza, empresas de control de plagas urbanas, asÃ­ como los equipos y maquinaria, y materiales propagativos como semillas, esquejes, tubÃ©rculo y plÃ¡ntulas.', 10, 7, 1),
(60, 2, 23, NULL, '61', 'Â¿Se garantiza que los insumos y productos adquiridos se encuentren registrados ante las autoridades competentes y esto puede ser verificable a travÃ©s de fichas tÃ©cnicas, listado oficial u otros medios?', 'F) Debe asegurarse que los insumos y productos adquiridos se encuentren registrados ante  las  autoridades competentes  y Ã©ste pueda ser verificable a travÃ©s de fichas tÃ©cnicas, listado oficial u otros medios.', 10, 8, 1),
(61, 2, 23, NULL, '62', 'Â¿La trazabilidad cumple con los siguientes requisitos: IdentificaciÃ³n mediante un cÃ³digo el lote y el origen del producto, Comunicar a travÃ©s de un medio impreso (etiquetas, papeletas, sellos, cÃ³digo de barras, entre otros) un cÃ³digo que indique el lote y origen del producto, Generar los registros suficientes que demuestren la lÃ­nea transportista utilizada y el comprador del producto, identificar mediante un listado la relaciÃ³n de empresas cliente?', 'La trazabilidad hacia adelante debe cumplir con los requisitos siguientes:\r\nA) IdentificaciÃ³n mediante un cÃ³digo el lote y el origen del producto.\r\nB) Comunicar a travÃ©s de un medio impreso (etiquetas, papeletas, sellos, cÃ³digo de barras, entre otros) un cÃ³digo que indique el lote y origen del producto. Esto deberÃ¡ mantenerse en cajas, pallets y/o PLU de productos.\r\nC) En caso de productos regulados fitosanitariamente podrÃ¡ utilizarse como identificaciÃ³n de origen el nÃºmero asignado por la DirecciÃ³n General de Sanidad Vegetal.', 10, 9, 1),
(62, 2, 23, NULL, '63', 'Â¿Cuenta con un listado de empresas cliente que incluya Nombre de la empresa, Representante legal, DirecciÃ³n, telÃ©fono, correo electrÃ³nico, Marca (s) del (os) productos, Mercado destino y marca, Puntos principales de distribuciÃ³n?', 'E) Debe identificar mediante un listado la relaciÃ³n de empresas cliente indicando lo siguiente:\r\n1.  Nombre de la empresa.\r\n2.  Representante legal.\r\n3.  DirecciÃ³n, telÃ©fono, correo electrÃ³nico.\r\n4.  Marca (s) del (os) productos.\r\n5.  Mercado destino y marca.\r\n6.  Puntos principales de distribuciÃ³n.', 10, 10, 1),
(63, 2, 23, NULL, '64', 'Â¿La empresa cuenta con un sistema de retiro de productos agrÃ­colas involucrados en contingencias sanitarias?', 'La empresa debe contar con un sistema de retiro de productos agrÃ­colas involucrados en contingencias sanitarias. El sistema debe cumplir con los requisitos siguientes:\r\nA) Procedimiento documentado que describa las acciones que la empresa realiza ante situaciones de contingencia de su producto.\r\nB) Registros que demuestren las acciones correctivas aplicadas.\r\nC) Informe de  resultados obtenidos ante  las  situaciones de contingencia reales o simuladas.', 10, 11, 1),
(64, 2, 23, NULL, '65', 'Â¿La  empresa  ha  realizado  y  documentado una  situaciÃ³n  simulada  de  contingencia,  que permita identificar con claridad la etapa del proceso donde se pudo contaminar el producto asÃ­ como las acciones correctivas aplicadas?', 'La empresa deberÃ¡ realizar y documentar una situaciÃ³n simulada de contingencia lo cual permita identificar con claridad la etapa del proceso donde se pudo contaminar el producto asÃ­ como las acciones correctivas aplicadas.', 10, 12, 1),
(65, 2, 24, NULL, '66', 'Â¿Se cuenta con una anÃ¡lisis de peligro y un plan tÃ©cnico integrado  por procedimientos operativos estandarizados, registros  y documentos generados, evidencias que demuestren que las acciones aplicadas son eficaces?', 'El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe realizar un anÃ¡lisis de peligros de las fuentes de agua empleadas por la empresa y determinar las medidas de control apropiadas a la condiciÃ³n productiva y que demuestre su eficacia en la prevenciÃ³n, reducciÃ³n y/o eliminaciÃ³n del contaminante valorado.\r\nEn base a lo anterior debe diseÃ±ar y aplicar un plan preventivo que contenga:\r\nâ€¢ Plan tÃ©cnico para el manejo del agua.\r\nâ€¢ Procedimientos Operativos Estandarizados que describe las medidas de control a aplicarse.\r\nâ€¢ Registros, y documentos.\r\nâ€¢ Evidencias que demuestren que las acciones aplicadas son eficaces como: anÃ¡lisis microbiolÃ³gicos de superficies de contacto, anÃ¡lisis fisicoquÃ­mico del agua (metales pesados, pH y concentraciÃ³n de sÃ³lidos solubles).\r\nâ€¢ Plan de CapacitaciÃ³n y reforzamiento de la informaciÃ³n al personal involucrado en esta materia.', 10, 1, 1),
(66, 2, 24, NULL, '67', 'Â¿Se  Identifica  las  fuente  de  agua  en  la  unidad  de empaque en la empresa, se valora la calidad fisicoquÃ­mica del agua tomando como referencia lo previsto en la NOM-127-SSA-1994?', 'Entre las acciones sugeridas para la prevenciÃ³n, reducciÃ³n y/o eliminaciÃ³n del contaminante en el agua son las siguientes (acciones sugeridas, no restrictivas):\r\n1. Identificar la fuente de abastecimiento de agua en la unidad de empaque.\r\n2. Valorar la calidad fisicoquÃ­mica del agua tomando como referencia lo previsto en la NOM-127-SSA1-1994. Esta no debe rebasar los lÃ­mites permisibles de la Norma Oficial de referencia.\r\n3.  Aplicar  las  acciones correctivas necesarias para  evitar  que  la calidad fisicoquÃ­mica genere un efecto adverso para el control de organismos patÃ³genos y sustancias quÃ­micas.\r\n4. Agua para uso en el empaque  y uso humano.', 5, 2, 1),
(67, 2, 24, NULL, '68', 'Â¿El agua para uso en el empaque y uso humano es potable y libre de organismos patÃ³genos, Coliformes totales y fecales?', 'a. Debe ser potable libre de organismos patÃ³genos, Coliformes totales y fecales segÃºn lo  dispuesto en  la NOM-127-SSA1-1994.\r\nb. El responsable tÃ©cnico debe valorar el mÃ©todo mÃ¡s apropiado para la prevenciÃ³n, reducciÃ³n y/o eliminaciÃ³n de los contaminantes valorados en la fuente de agua sin perjuicio de la funciÃ³n productiva. Este tratamiento debe ser validado y debe demostrar su eficacia.\r\nc. Los  recipientes  y  contenedores  que  almacenen  agua para este propÃ³sito deben permanecer limpios,\r\nprotegidos contra el ingreso de animales domÃ©sticos, silvestres, seres humanos, escurrimientos y rociado de sustancias quÃ­micas.\r\nd. Debe evitar el almacenamiento de sustancias agroquÃ­micas, abonos orgÃ¡nicos, estaciones sanitarias, maquinaria, herramientas y equipos agrÃ­colas cercanos a fuentes de agua y depÃ³sitos de almacenamiento.\r\ne. Debe aplicar un tratamiento preventivo al agua para estos fines con la capacidad suficiente para asegurar la calidad y la reducciÃ³n del riesgo del agua.', 10, 3, 1),
(68, 2, 24, NULL, '69', 'Â¿La  validaciÃ³n  de  la  eficacia  de  los  tratamientos aplicados al  agua,  estÃ¡  ajustada  a  los indicadores dispuestos en la NOM-127-SSA1-2002?', 'La validaciÃ³n de la eficacia de los tratamientos aplicados al agua debe ajustarse a los indicadores dispuesto en la NOM-127-SSA1-1994.', 10, 4, 1),
(69, 2, 25, 358, '70', 'Â¿Se cuenta con una anÃ¡lisis de peligro y un plan tÃ©cnico integrado  por procedimientos operativos estandarizados, registros  y documentos generados, asÃ­ como su documentaciÃ³n soporte, fichas tÃ©cnicas de los productos utilizados, plan de capacitaciÃ³n y reforzamiento de la informaciÃ³n al personal involucrado en esta materia?', 'Debe realizar un anÃ¡lisis de peligros, que considere el manejo de sustancias quÃ­micas utilizadas en la empresa.\r\nEn base a lo anterior debe diseÃ±ar y aplicar un plan preventivo que contenga:\r\n* Plan tÃ©cnico para el manejo de sustancias quÃ­micas.\r\n* Procedimientos Operativos Estandarizados que describe las medidas de control a aplicarse.\r\n* Registros y documentos generados, asÃ­ como su documentaciÃ³n soporte.\r\n* Fichas tÃ©cnicas de los productos utilizados.\r\n* Plan de capacitaciÃ³n y reforzamiento de la informaciÃ³n al personal involucrado en esta materia.', 10, 1, 1),
(70, 2, 25, 349, '71', 'Â¿La elecciÃ³n de los detergentes y desinfectantes se basa en las caracterÃ­sticas de la superficie a limpiar y la naturaleza de la suciedad a eliminar y estÃ¡n aprobados para su uso en establecimientos de alimentos?', 'La elecciÃ³n de los detergentes y desinfectantes debe basarse en las caracterÃ­sticas de la superficie a limpiar y la naturaleza de la suciedad a eliminar.', 10, 1, 1),
(71, 2, 25, 349, '72', 'Â¿Cuenta la Empresa con procedimientos para la preparaciÃ³n de soluciones desinfectantes y detergentes que aplican en el programa de higiene?', 'El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe elaborar procedimientos para la preparaciÃ³n de Sustancias desinfectantes que aplican en el programa de higiene.', 10, 2, 1),
(72, 2, 25, 350, '73', 'Â¿En  el  caso  de  realizar  tratamientos  fungicidas  y  bactericidas,  los  productos  estÃ¡n permitidos por la legislaciÃ³n nacional?', 'En  el  caso  de  realizar  tratamientos  fungicidas  y  bactericidas, dichos productos deberÃ¡n estar permitidos por la legislaciÃ³n nacional.', 10, 1, 1),
(73, 2, 25, 350, '74', 'Â¿Independientemente  de  su  origen  orgÃ¡nico  o  de  sÃ­ntesis  quÃ­mica,  se  demuestra  la inocuidad de estas sustancias?', 'Se debe demostrar independientemente  de  su  origen  orgÃ¡nico  o  de  sÃ­ntesis  quÃ­mica, la inocuidad de estas sustancias.', 10, 2, 1),
(74, 2, 25, 350, '75', 'Â¿Se cuenta con registros que incluyan el producto empleado, dosis, tratamiento deseado, Ã¡rea o punto de uso, fecha, lote, responsable?', 'Registros y documentaciÃ³n de soporte que demuestre que las acciones aplicadas se realizan y que son eficaces.', 10, 3, 1),
(75, 2, 25, 350, '76', 'Â¿Los registros estÃ¡n respaldados por una justificaciÃ³n tÃ©cnica emitida, factura y/o nota de compra de los productos registrados?', 'Los registros se deberÃ¡n respaldar mediante una justificaciÃ³n tÃ©cnica.', 10, 4, 1),
(76, 2, 25, 351, '77', 'Â¿Se  cuenta  con  un  registro  de  los  productos  adquiridos,  en  el  que  se  identifique  el proveedor, producto (marca comercial y nombre tÃ©cnico), fecha de adquisiciÃ³n, factura o nota de compra, lote de producto, responsable de recepciÃ³n?', 'Debe llevar un registro de los productos adquiridos indicando proveedor, producto (marca comercial y nombre tÃ©cnico), fecha de adquisiciÃ³n, factura o nota de compra, lote de producto  y responsable de recepciÃ³n.', 10, 1, 1),
(77, 2, 25, 352, '78', 'Â¿La empresa aplica un programa de capacitaciÃ³n anual a los trabajadores sobre las medidas de seguridad que deben adoptarse durante el uso y manejo de quÃ­micos?', 'La empresa debe aplicar un programa de capacitaciÃ³n anual a los trabajadores sobre las medidas de seguridad que deben adoptarse durante el uso y manejo de agroquÃ­micos.', 10, 1, 1),
(78, 2, 25, 352, '79', 'Â¿Se  ha  realizado  la  entrega  de  un  instructivo  que  indique  las  acciones  y  precauciones mÃ­nimas que el trabajador debe seguir durante el uso y manejo confiable de agroquÃ­micos y se ha generado evidencia documental de esta acciÃ³n?', 'Debe entregar un instructivo que indique las acciones y precauciones mÃ­nimas que el trabajador debe seguir durante el uso y manejo de sustancias quÃ­micas. Debe generar evidencia documental de esta acciÃ³n. El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe asegurarse que todos los trabajadores   utilizan   los   Equipos   de   ProtecciÃ³n durante la aplicaciÃ³n y preparaciÃ³n de sustancias de quÃ­micas. Debe generar una evidencia documental o visual de esta acciÃ³n.', 5, 2, 1),
(79, 2, 26, NULL, '80', 'Â¿Se cuenta con una anÃ¡lisis de peligro y un plan tÃ©cnico integrado  por procedimientos operativos estandarizados, registros  y documentos generados?', 'Las empresas deben valorar el riesgo que durante esta fase productiva los productos puedan ser contaminados por peligros de  tipo biolÃ³gico, quÃ­mico y/o fÃ­sico asociados.\r\nEn base al anÃ¡lisis de peligros, la empresa debe diseÃ±ar un plan de prevenciÃ³n y control de los contaminantes valorados lo cual debe cumplir con lo siguiente:\r\nA) ElaboraciÃ³n  de  un  plan  tÃ©cnico  que  describa  las  acciones, mÃ©todos y criterios a aplicarse durante esta etapa.\r\nB) El  procedimiento  que  describa  las  medidas  de  control  a aplicarse.\r\nC) Registros y documentaciÃ³n de soporte que demuestre que las acciones aplicadas se realizan y que son eficaces.\r\nD) Plan de CapacitaciÃ³n del personal involucrado en esta etapa.', 10, 1, 1),
(80, 2, 26, NULL, '81', 'Â¿Los productos agrÃ­colas empacados cumplen con el intervalo de seguridad entre el corte del producto y la Ãºltima aspersiÃ³n de agroquÃ­micos?', 'Los productos agrÃ­colas empacados deberÃ¡n cumplir con lo siguiente:\r\nA) Asegurarse que cumplieron con el Intervalo de Seguridad entre el corte del producto y la Ãºltima aspersiÃ³n de agroquÃ­micos.\r\nB) Identifique las Unidades Productivas que le abastecen de productos de origen agrÃ­cola.\r\nC) No deben empacarse productos que observen la presencia de materiales ajenos a su composiciÃ³n natural (residuos de agroquÃ­micos, materia fecal, tierra, etc.). Estos deben ser destruidos fuera de la unidad de empaque.', 5, 2, 1),
(81, 2, 26, NULL, '82', 'Â¿Se aplican medidas preventivas que eviten que el producto entre en contacto directo o indirecto con sustancias, materiales y superficies que lo puedan contaminar?', 'D) Aplicar las medidas preventivas que eviten que el producto entre en contacto directo o indirecto con sustancias, materiales y superficies que lo puedan contaminar.\r\nE) Debe evitarse la aplicaciÃ³n de tratamientos quÃ­micos durante el empacado de productos. AdemÃ¡s de estar autorizados por la autoridad nacional competente en el tema debe asegurase que se cumpliÃ³ con el periodo de reentrada especificado para el producto utilizado para reiniciar con el empaque.', 5, 3, 1),
(82, 2, 223, NULL, '83', 'Â¿Se cuenta con una anÃ¡lisis de peligro y un plan tÃ©cnico integrado  por procedimientos operativos estandarizados, registros  y documentos generados, evidencias que demuestren que las acciones aplicadas son eficaces?', 'El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n de la empresa debe valorar mediante un anÃ¡lisis de peligros los posibles contaminantes que pueden adquirirse mediante el uso de vehÃ­culos destinados por la empresa para este fin.\r\nDebe elaborar un plan tÃ©cnico y procedimientos documentados que describan las acciones especÃ­ficas para reducir el riesgo de contaminaciÃ³n valorado asÃ­ como los registros que demuestren su cumplimiento.', 10, 1, 1),
(83, 2, 223, NULL, '84', 'Â¿El personal responsable del transporte y los cargadores, estÃ¡ capacitados sobre las prÃ¡cticas mÃ­nimas de seguridad e higiene que deben cumplirse durante el transporte del producto?', 'El personal responsable del transporte y os cargadores deben estar capacitados sobre las prÃ¡cticas mÃ­nimas de seguridad e higiene que deben cumplirse  durante   el   transporte   del   producto   y generar los registros suficientes que permitan corroborar el cumplimiento de estas acciones.', 5, 2, 1),
(84, 2, 18, 333, '85', 'Â¿Se han implementado barreras fÃ­sicas de protecciÃ³n que impidan o reduzcan las posibilidades de ingreso de animales domÃ©sticos, silvestres, escurrimientos u otros factores que pudieran representar un  riesgo de introducir un  contaminante de origen quÃ­mico y biolÃ³gico a las unidades de empaque?', 'El profesional en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n, debe definir el tipo de barrera fÃ­sica que debe aplicarse en la Unidad Productiva. La barrera fÃ­sica debe tener la capacidad de impedir el ingreso de animales domÃ©sticos y silvestres del exterior, escurrimientos, personas ajenas a la Unidad Productiva u otros factores de riesgo identificados que puedan posicionar o introducir un contaminante de origen biolÃ³gico y quÃ­mico a la Unidad Productiva, a  las  fuentes  de  agua,  Ã¡reas  de empacado.\r\nEl responsable debe asegurarse y demostrar que la barrera de protecciÃ³n se mantiene en buen estado fÃ­sico y que asegura la eficacia para lo que fue generada.', 10, 1, 2),
(85, 2, 18, 334, '86', 'Â¿Las estaciones sanitarias estÃ¡n construidas con materiales que faciliten su lavado y desinfecciÃ³n, asÃ­  como  con  la  capacidad  para  contener derrames  generados durante  su higienizaciÃ³n?', 'Las Estaciones Sanitarias deberÃ¡n estar construidas con materiales que faciliten su lavado y desinfecciÃ³n, asÃ­ como con la capacidad para contener derrames generados durante su higienizaciÃ³n. De la misma manera deberÃ¡n cumplir con los requisitos establecidos en el punto 7.0 de la NOM-120-SSA1-1994.', 10, 1, 2),
(86, 2, 18, 334, '87', 'Â¿Las estaciones sanitarias estÃ¡n instaladas a una distancia no mayor a 400 m del Ã¡rea de empaque,  diferenciadas por sexo y respetando la relaciÃ³n de un sanitario por cada 20 trabajadores, ya sean fijas, semifijas o portÃ¡tiles y en caso de no cumplir con los criterios de distancia se justifica?', 'Las instalaciones sanitarias deben Instalarse a distancias no mayores a 400 metros de empaque, estar diferenciadas por sexo y respetar la relaciÃ³n de un sanitario por cada 20 trabajadores. Las estaciones sanitarias podrÃ¡n ser fijas, semifijas o portÃ¡tiles.', 10, 2, 2),
(87, 2, 18, 334, '88', 'Â¿Las estaciones sanitarias estÃ¡n equipadas con agua potable, jabÃ³n liquido, toallas de papel secante, papel higiÃ©nico, lavabo, cesto de basura con bolsa plÃ¡stica, gel antibacterial?', 'Las Estaciones Sanitarias deben estar equipadas con agua potable, jabÃ³n liquido, toallas de papel, papel higiÃ©nico, lavabo, cesto de basura con bolsa plÃ¡stica, gel antibacterial, este Ãºltimo en el periodo de cosecha o cuando los trabajadores entren en contacto directo con el producto.', 10, 3, 2),
(88, 2, 18, 334, '89', 'Â¿En caso de utilizar fosas sÃ©pticas plÃ¡sticas o de concreto, Ã©stas son completamente cerradas para asegurar que la materia fecal o sus biosÃ³lidos entren en contacto directo con el ambiente para prevenir la contaminaciÃ³n a travÃ©s de la materia fecal?', 'Para prevenir la contaminaciÃ³n a travÃ©s de la materia fecal asociado a las fosas sÃ©pticas, estas deberÃ¡n cumplir con lo siguiente: Utilizar fosas sÃ©pticas plÃ¡sticas o de concreto completamente cerradas las cuales deberÃ¡n asegurar que la materia fecal o sus bio sÃ³lidos eviten el contacto directo con el ambiente.  Revisar NOM-006- CONAGUA-1997', 10, 4, 2);
INSERT INTO `CAT_PREGUNTAS` (`id_pregunta`, `id_version`, `id_modulo`, `id_subModulo`, `numPregunta`, `pregunta`, `recomendacion`, `valor`, `orden`, `id_estructuraDiag`) VALUES
(89, 2, 18, 334, '90', 'Â¿Las estaciones sanitarias estÃ¡n libres de fugas, derrames, deterioros u otro tipo de daÃ±os que impliquen un factor de riesgo de contaminaciÃ³n a los productos?', 'Las estaciones sanitarias deberÃ¡n encontrarse libres de fugas, derrames, deterioros u otro tipo de daÃ±os que  impliquen  un  factor  de  Riesgo  de  ContaminaciÃ³n  a  los productos de origen agrÃ­cola.', 10, 5, 2),
(90, 2, 18, 334, '91', 'Â¿Se mantienen seÃ±alamientos grÃ¡ficos suficientes y pertinentes para recordar las medidas de higiene que deben cumplir los trabajadores durante el uso de las estaciones sanitarias?', 'La empresa debe contar con los seÃ±alamientos grÃ¡ficos suficientes y pertinentes para recordar las medidas de higiene que deben cumplir los trabajadores durante su uso.', 10, 6, 2),
(91, 2, 18, 334, '92', 'Â¿La empresa cuenta con el equipo identificado, asÃ­ como los insumos requeridos  para realizar la limpieza y desinfecciÃ³n de las estaciones sanitarias?', 'La empresa debe contar con los materiales, equipos identificados  e insumos requeridos para la higienizaciÃ³n de las Estaciones Sanitarias.', 10, 7, 2),
(92, 2, 18, 335, '93', 'Â¿Se cuenta con Ã¡reas destinadas para el consumo de alimentos de los trabajadores, con mobiliario suficiente?', 'Las Unidades Productivas o Ã¡reas integrales deben contar con Ã¡reas destinadas para el consumo de alimentos de los trabajadores.', 10, 1, 2),
(93, 2, 18, 335, '94', 'Â¿El Ã¡rea para el consumo de alimentos, estÃ¡ construida con material que facilite su lavado y desinfecciÃ³n?', 'Las Ã¡reas destinadas para el consumo de alimentos pueden ser construidas con: material de concreto, lamina galvanizada, toldos o cualquier otro material que facilite su lavado y desinfecciÃ³n.', 10, 2, 2),
(94, 2, 18, 335, '95', 'Â¿Dicha Ã¡rea se encuentra fuera del  Ã¡rea de empaque, almacenamiento de  materiales de  embalaje, sustancias quÃ­micas u  otros elementos que pudieran  representar  un  riesgo  de  contaminaciÃ³n del  producto,  daÃ±o  al  trabajador y/o deterioro del ambiente?', 'El Ã¡rea de consumo de alimentos no  debe estar  dentro  del  Ã¡rea de empacado, de  almacenamiento de  materiales  de  embalaje, sustancias quÃ­micas u otros elementos que pudieran representar un Riesgo de ContaminaciÃ³n del producto, daÃ±o al trabajador y/o deterioro del ambiente.', 10, 3, 2),
(95, 2, 18, 335, '96', 'Â¿El Ã¡rea de consumo de alimentos cuenta con depÃ³sitos de basura, estaciÃ³n para lavado de manos, equipo de limpieza y mobiliario suficiente para uso de los trabajadores?', 'Dicha Ã¡rea debe contar con materiales y accesorios para la higienizaciÃ³n de la instalaciÃ³n, cestos para el depÃ³sito de basura, accesorios que eviten el derrame de lÃ­quidos durante su higienizaciÃ³n, separaciÃ³n fÃ­sica entre el Ã¡rea de depÃ³sito de objetos personales y el Ã¡rea de consumo de alimentos.', 10, 4, 2),
(96, 2, 18, 336, '97', 'Â¿Se cuenta  con  Ã¡reas  especÃ­ficas  para  el  depÃ³sito  de  objetos personales, debidamente identificados y con seÃ±alamientos grÃ¡ficos?', 'Las Unidades Productivas deben contar con Ã¡reas especÃ­ficas para el depÃ³sito de objetos personales, debidamente identificados y con seÃ±alamientos grÃ¡ficos.', 10, 1, 2),
(97, 2, 18, 336, '98', 'Â¿Estas Ã¡reas se encuentran localizadas fuera del Ã¡rea de empaque de productos, almacenamiento de sustancias quÃ­micas u otros espacios que puedan representar un riesgo de daÃ±o a la salud del trabajador y de contaminaciÃ³n de los productos?', 'Las Ã¡reas de depÃ³sito de objetos personales no deben localizarse dentro  del  Ã¡rea  de  empacado  de productos,  Ã¡rea  de  almacenamiento  de  sustancias  quÃ­micas  u otros espacios que puedan representar un riesgo de daÃ±o a la salud del trabajador y de contaminaciÃ³n de los productos.', 10, 2, 2),
(98, 2, 18, 336, '99', 'Â¿El Ã¡rea de depÃ³sito de objetos personales se encuentra fÃ­sicamente delimitada (Lockers, mÃ©nsulas, guardarropa, etc.) del Ã¡rea de consumo de alimentos y estaciones sanitarias?', 'El Ã¡rea de depÃ³sito de objetos personales podrÃ¡ compartir espacios con el Ã¡rea de consumo de alimentos y estaciones sanitarias, siempre y cuando Ã©stas se encuentren fÃ­sicamente delimitadas (estante, mÃ©nsulas, guardarropa, etc.).', 10, 3, 2),
(99, 2, 18, 337, '100', 'Â¿El Ã¡rea de almacenamiento de equipos y herramientas de trabajo se localiza fuera del Ã¡rea de producciÃ³n, almacenamiento, empaque de productos, consumo de alimentos y de almacenamiento de sustancias quÃ­micas?', 'Las  empresas  que  utilicen  equipos y herramientas  en  los  procesos productivos deberÃ¡n asignar espacios especÃ­ficos para su almacenamiento y/o resguardo. Los espacios para equipos y herramientas deberÃ¡n estar localizados fuera del Ã¡rea de producciÃ³n, almacenamiento y empacado de productos, consumo de alimentos y de almacenamiento de sustancias quÃ­micas. Ver NOM-004-STPS-1999.', 10, 1, 2),
(100, 2, 18, 337, '101', 'Â¿Esta Ã¡rea cuenta con piso de concreto y techado, con espacios diferenciados  para lubricantes,  combustibles  y  reparaciones  menores,  con  canaletas  de  contenciÃ³n  para contener derrames de lubricantes, grasas y combustibles?', 'Esta Ã¡rea deberÃ¡ estar techada y preferentemente con piso de concreto. Es necesario diferenciar los espacios asignados para lubricantes, combustibles y reparaciones menores y debe de contar con canaletas de contenciÃ³n para derrames de lubricantes, grasas y combustibles.', 10, 2, 2),
(101, 2, 18, 337, '102', 'Â¿Las reparaciones, mantenimiento de equipos son realizadas fuera de la unidad productiva y en lugares que no representen riesgos de contaminaciÃ³n a productos, personas y/o manto freÃ¡tico?', 'Las reparaciones, mantenimiento y calibraciones de maquinaria y equipos deben realizarse fuera de la Unidad Productiva y en lugares que no representen riesgos de contaminaciÃ³n a productos, personas y/o manto freÃ¡tico.', 10, 3, 2),
(102, 2, 18, 337, '103', 'Â¿La empresa asigna espacios para el almacenamiento de herramientas de trabajo, que no son compartidos  con   sustancias quÃ­micas,  equipos  de   protecciÃ³n,  almacenamiento  y empaque de productos vegetales?', 'La  empresa  debe  asignar  espacios  para  el  almacenamiento de herramientas de trabajo, el cual no podrÃ¡ ser compartido con sustancias agroquÃ­micas, sustancias desinfectantes, detergentes, equipos de aplicaciÃ³n, de protecciÃ³n, almacenamiento y empacado de productos de origen vegetal.', 10, 4, 2),
(103, 2, 18, 343, '104', 'Â¿La unidad de empaque cuenta con un Ã¡rea especÃ­fica para el almacenamiento y/o depÃ³sito temporal de productos cosechados?', 'Las Unidades Productivas deberÃ¡n contar con un Ã¡rea especÃ­fica para el almacenamiento y/o depÃ³sito temporal de productos cosechados.', 10, 1, 2),
(104, 2, 18, 343, '105', 'Â¿El Ã¡rea para empaque y almacenamiento temporal designada, se utiliza  exclusivamente para Ã©ste propÃ³sito, estÃ¡ protegida contra el ingreso de agentes que puedan contaminar el producto como fauna domÃ©stica y silvestre?', 'El Ã¡rea para empacado y almacenamiento  deberÃ¡  destinarse  exclusivamente para  este  propÃ³sito, estar protegida contra el ingreso de agentes que puedan contaminar el producto como fauna domestica y silvestre y fuera del Ã¡rea activa de cosecha. El espacio no debe ser compartido con sustancias quÃ­micas u otras sustancias y materiales que puedan contaminar los productos de origen agrÃ­cola. El Ã¡rea de empacado deberÃ¡n cumplir con lo dispuesto en la NOM-120-SSA1-1994 de la Secretaria de Salud.', 10, 2, 2),
(105, 2, 18, 343, '106', 'Â¿Cuenta con piso firme que pueda higienizarse y con una estaciÃ³n sanitaria para la higiene de los trabajadores, ademÃ¡s se evita el cruce de producto terminado con la materia prima?', 'Debe tener piso firme y/o de concreto que pueda higienizarse, debe contar con estaciÃ³n sanitaria para la higiene de los trabajadores o ubicarse en un Ã¡rea cercana a ella, debe existir un flujo que evite el cruce de producto terminado con la materia prima.', 10, 3, 2),
(106, 2, 18, 359, '107', 'Â¿Todas las instalaciones de la unidad productiva estÃ¡n identificadas y con los seÃ±alamientos grÃ¡ficos que les corresponda?', 'Para la identificaciÃ³n y seÃ±alizaciÃ³n de las instalaciones deberÃ¡n apegarse a lo dispuesto en la NOM-026-STPS-1994.', 10, 1, 2),
(107, 2, 18, 344, '108', 'Â¿Demuestra el personal involucrado que fue capacitado y que sabe ejecutar la acciÃ³n en la que ha sido capacitado?', 'El personal involucrado debe demostrar que fue capacitado y que sabe ejecutar la acciÃ³n en la que fue capacitado.', 10, 1, 2),
(108, 2, 19, 357, '109', 'Â¿Se garantiza que la concentraciÃ³n deseada se mantiene durante el tiempo requerido para su acciÃ³n desinfectante asÃ­ como la reducciÃ³n de la presencia del contaminante valorado?', 'El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe asegurarse que la concentraciÃ³n deseada se mantiene durante el tiempo requerido para su acciÃ³n desinfectante asÃ­ como que Ã©sta reduce la presencia del contaminante valorado.', 5, 1, 2),
(109, 2, 19, 357, '110', 'Â¿Los utensilios, insumos, recipientes y productos utilizados para la preparaciÃ³n, almacenamiento y monitoreo de las sustancias desinfectantes son manejadas fuera del Ã¡rea productiva, de empaque o de almacenamiento de productos vegetales?', 'Los utensilios, insumos, recipientes y productos utilizados para la preparaciÃ³n, almacenamiento y monitoreo de las sustancias desinfectantes deberÃ¡n  manejarse fuera  del  Ã¡rea de empacado o de almacenamiento de productos de origen agrÃ­cola.', 10, 2, 2),
(110, 2, 19, 357, '111', 'Â¿El agua utilizada para su uso en el programa de higiene en instalaciones, preparaciÃ³n de sustancias desinfectantes, y trabajadores es potable segÃºn lo dispuesto por la NOM-127- SSA1-1994?', 'El agua utilizada para su uso en el programa de higiene en instalaciones, preparaciÃ³n de sustancias desinfectantes y trabajadores debe ser potable segÃºn lo dispuesto por la NOM-127- SSA1-1994.', 10, 3, 2),
(111, 2, 19, 346, '112', 'Â¿Se mantienen las instalaciones limpias, durante el proceso productivo y se limpian al menos una vez al mes durante el periodo en que no se encuentran en fase productiva?', 'Las instalaciones deben mantenerse limpias durante el proceso productivo y limpiarse al menos una vez al mes durante el periodo en que no se encuentre en fase productiva.', 5, 1, 2),
(112, 2, 19, 346, '113', 'Â¿Se garantiza que los residuos derivados de la higiene de las instalaciones no ingresan al Ã¡rea activa de empacado, almacenes o Ã©stos sean vertidos sobre fuentes de agua para uso agrÃ­cola y humano?', 'Debe asegurarse que los residuos derivados de la higiene de las instalaciones no ingresen al Ã¡rea de empacado, Ã¡rea productiva o Ã©stos sean vertidos sobre fuentes de agua para uso agrÃ­cola y humano.', 10, 2, 2),
(113, 2, 19, 346, '114', 'Â¿Los detergentes y desinfectantes utilizados, no contienen aromatizantes y son seleccionados de acuerdo con la superficie a higienizar?', 'Los detergentes y desinfectantes deben ser seleccionados cuidadosamente para lograr el fin perseguido. No deben contener aromatizantes y su alcalinidad o acidez dependerÃ¡ de la superficie a higienizar.', 10, 3, 2),
(114, 2, 19, 347, '115', 'Â¿Se demuestra que las prÃ¡cticas de higiene se  mantienen en todo momento durante el desempeÃ±o del trabajo en el interior de las unidades productivas tanto el personal de base, eventual y ocasional?', 'Debe asegurarse que las prÃ¡cticas de higiene se mantienen en todo momento durante el desempeÃ±o del trabajo en el interior de las Unidades Productivas tanto el personal de base, eventual y ocasional.', 10, 1, 2),
(115, 2, 19, 347, '116', 'Â¿La empresa cuenta con un reglamento de trabajo que indique las prÃ¡cticas de higiene que deben asumir los trabajadores durante el desempeÃ±o de sus actividades y estancia en el empaque, que sea entendible por los trabajadores usando medios grÃ¡ficos o cualquier otro medio que facilite su entendimiento?', 'La empresa debe contar con un reglamento de trabajo que indique las prÃ¡cticas de higiene que deben asumir los trabajadores durante el   desempeÃ±o  de   sus   actividades  y  estancia  en   la   Unidad de Empaque. Este debe ser entendible por los trabajadores usando medios grÃ¡ficos o cualquier otro medio que facilite su entendimiento. (ANEXO Reglamento de Empaque)', 10, 2, 2),
(116, 2, 19, 348, '117', 'Â¿La unidad de empaque se mantiene libre de basura, residuos de cosecha, piedras amontonadas, materiales en desuso, residuos, recipientes, contenedores de lÃ­quidos y todo aquello que pueda constituir una fuente de contaminaciÃ³n?', 'El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe revisar de acuerdo con la frecuencia establecida en el plan tÃ©cnico, la Unidad Empaque y debe asegurarse que Ã©sta se mantiene limpia y libre de basura.', 5, 1, 2),
(117, 2, 222, NULL, '118', 'Â¿La unidad de empaque se conserva limpia, evitando la presencia de maquinaria en desuso, maleza en exceso, restos de alimentos y otros que puedan atraer o servir como hÃ¡bitat a animales y plagas?', 'La unidad de empaque debe conservarse limpia, evitando la presencia de maquinaria en desuso, maleza en exceso, restos de alimentos y otros que puedan atraer o servir como hÃ¡bitat a animales y plagas.', 10, 1, 2),
(118, 2, 222, NULL, '119', 'Â¿Las fuentes de agua, Ã¡reas de empaque, depÃ³sito temporal de producto, almacenamiento de materiales de empaque, se han protegido contra el ingreso de todo tipo de animales?', 'Deben protegerse las fuentes de agua, Ã¡reas de empacado, Ã¡reas de depÃ³sito temporal de producto, Ã¡rea de almacenamiento de materiales de empaque, material de empacado contra el ingreso de todo tipo de animales.', 10, 2, 2),
(119, 2, 222, NULL, '120', 'Â¿Se aplica el control de plagas a todas las Ã¡reas del establecimiento, recepciÃ³n de materia prima, almacÃ©n, proceso, almacÃ©n de producto terminado, distribuciÃ³n, comedor, oficinas e inclusive vehÃ­culos de acarreo y reparto?', 'El control de plagas serÃ¡ aplicable a todas las Ã¡reas del establecimiento, recepciÃ³n de materia prima, almacÃ©n, proceso, almacÃ©n de producto terminado, distribuciÃ³n, comedor, oficinas, e inclusive vehÃ­culos de acarreo y reparto.', 10, 3, 2),
(120, 2, 222, NULL, '121', 'Â¿El  reglamento de  los  trabajadores indica  la  prohibiciÃ³n a  las  personas de  ingresar  con animales domÃ©sticos y silvestres a las Ã¡reas almacenamiento, empaque y Ã¡reas de riesgo para contaminaciÃ³n del producto?', 'El reglamento de los trabajadores debe indicar con claridad la prohibiciÃ³n a las personas de ingresar con animales domÃ©sticos y silvestres a las Ã¡reas de almacenamiento, empacado y Ã¡reas de riesgo para la contaminaciÃ³n del producto.', 10, 4, 2),
(121, 2, 222, NULL, '122', 'Â¿Se evita el uso de cebos envenenados en Ã¡rea de  producciÃ³n, almacenamiento de productos vegetales, de material de empaque y  embalaje, empaque (Interiores)?', 'Debe evitarse el uso de cebos envenenados en las siguientes Ã¡reas:\r\na. Ãreas de almacenamiento de productos de origen agrÃ­cola y de material de empaque y embalaje.\r\nb. De empacado (Interiores).', 10, 5, 2),
(122, 2, 222, NULL, '123', 'Â¿Las trampas situadas en interiores estÃ¡n identificadas y colocadas lo mÃ¡s cercano posible a las paredes y a las puertas de entrada o salida y formando un cerco interno?', 'En estas fases y/o Ã¡reas deben utilizar trampas fÃ­sicas y reforzar las prÃ¡cticas de higiene.Las  trampas  deben  ser  identificadas  y  colocadas  cerca  a  las paredes, puertas de entrada o salida y hacer un cerco interno.', 10, 6, 2),
(123, 2, 222, NULL, '123', 'Â¿Las trampas situadas en interiores estÃ¡n identificadas y colocadas lo mÃ¡s cercano posible a las paredes y a las puertas de entrada o salida y formando un cerco interno?', 'En estas fases y/o Ã¡reas deben utilizar trampas fÃ­sicas y reforzar las prÃ¡cticas de higiene.Las  trampas  deben  ser  identificadas  y  colocadas  cerca  a  las paredes, puertas de entrada o salida y hacer un cerco interno.', 10, 6, 2),
(124, 2, 222, NULL, '124', 'Â¿Las superficies, Ã¡reas de contacto y unidades empaque, se mantienen limpias de manera permanente?', 'Las superficies y Ã¡reas de contacto y Unidades de Empaque deben mantenerse limpias de manera permanente.', 10, 7, 2),
(125, 2, 20, NULL, '125', 'Â¿Se demuestra la capacitaciÃ³n a empleados permanentes y eventuales, al inicio, durante la temporada, cada vez que ingresa personal y cuando se realizan cambios en los procedimientos?', 'Se debe capacitar a empleados permanentes y eventuales, al inicio, durante la temporada, cada vez que ingrese personal y cuando se realicen cambios en los procedimientos.', 5, 1, 2),
(126, 2, 23, NULL, '126', 'Â¿La trazabilidad cumple con los siguientes requisitos: IdentificaciÃ³n mediante un cÃ³digo el lote y el origen del producto, Comunicar a travÃ©s de un medio impreso (etiquetas, papeletas, sellos, cÃ³digo de barras, entre otros) un cÃ³digo que indique el lote y origen del producto, Generar los registros suficientes que demuestren la lÃ­nea transportista utilizada y el comprador del producto, identificar mediante un listado la relaciÃ³n de empresas cliente?', 'La trazabilidad hacia adelante debe cumplir con los requisitos siguientes:\r\na. IdentificaciÃ³n mediante un cÃ³digo el lote y el origen del producto.\r\nb. Comunicar a travÃ©s de un medio impreso (etiquetas, papeletas, sellos, cÃ³digo de barras, entre otros) un cÃ³digo que indique el lote y origen del producto.\r\nc. En caso de productos regulados fitosanitariamente podrÃ¡ utilizarse como identificaciÃ³n de origen el nÃºmero asignado por la DirecciÃ³n General de Sanidad Vegetal.\r\nd. Generar los registros suficientes que demuestren la lÃ­nea transportista utilizada y el comprador del producto. Este Ãºltimo puede ser la empacadora destino, el distribuidor mayorista, el acopiador mayorista o minorista.\r\ne. Debe identificar mediante un listado la relaciÃ³n de empresas cliente indicando lo siguiente:\r\n1. Nombre de la empresa.\r\n2. Representante legal.\r\n3. DirecciÃ³n, telÃ©fono, correo electrÃ³nico.\r\n4. Marca (s) del (os) productos.\r\n5. Mercado destino y marca.\r\n6. Puntos principales de distribuciÃ³n.\r\nf. Las empresas podrÃ¡n comunicar a sus consumidores a travÃ©s de medios electrÃ³nicos la informaciÃ³n mÃ­nima que permita identificar el origen y las condiciones bajo las cuales se genero un producto agrÃ­cola.', 10, 1, 2),
(127, 2, 23, NULL, '127', 'Â¿El cÃ³digo que indica el lote y origen del producto, se mantiene en cajas, pallets y/o PLU de productos?', 'Mantener en cajas, pallets y/o PLU de productos el cÃ³digo que indica el lote y origen del producto.', 10, 2, 2),
(128, 2, 24, NULL, '128', 'Â¿Se  Identifica  las  fuente  de  agua  en  la  unidad  de empaque en la empresa, se valora la calidad fisicoquÃ­mica del agua tomando como referencia lo previsto en la NOM-127-SSA-1994?', 'Entre las acciones sugeridas para la prevenciÃ³n, reducciÃ³n y/o eliminaciÃ³n del contaminante en el agua son las siguientes (acciones sugeridas, no restrictivas):\r\n1. Identificar la fuente de abastecimiento de agua en la unidad de empaque.\r\n2. Valorar la calidad fisicoquÃ­mica del agua tomando como referencia lo previsto en la NOM-127-SSA1-1994. Esta no debe rebasar los lÃ­mites permisibles de la Norma Oficial de referencia.\r\n3.  Aplicar  las  acciones correctivas necesarias para  evitar  que  la calidad fisicoquÃ­mica genere un efecto adverso para el control de organismos patÃ³genos y sustancias quÃ­micas.\r\n4. Agua para uso en el empaque  y uso humano.', 5, 1, 2),
(129, 2, 24, NULL, '129', 'Â¿Se realizan tratamientos al agua de manejo en el empaque que prevengan, reduzcan y/o eliminen los contaminantes?', 'a. Debe aplicarse un tratamiento preventivo al agua destinada para manejo que reduzca la presencia de contaminantes quÃ­micos y/o fÃ­sicos mediante el uso de mÃ©todos como FiltraciÃ³n (membranas, arena, carbÃ³n activado), Tratamiento quÃ­mico (Uso de sustancias quÃ­micas).\r\nb.   Debe evitar que las sustancias quÃ­micas aplicadas en el tratamiento del agua para manejo no representen un riesgo de contaminaciÃ³n al producto o al consumidor.\r\nc.   Debe evitar el encharcamiento del agua en la Unidad Empaque durante el proceso de producciÃ³n del producto.', 10, 2, 2),
(130, 2, 24, NULL, '130', 'Â¿El tratamiento preventivo del agua se realiza lo mÃ¡s cercano al punto de uso o en el lugar preciso donde posterior a Ã©l la probabilidad de recontaminaciÃ³n se reduce?', 'El tratamiento preventivo del agua debe realizarse lo mÃ¡s cercano  al  punto  de  uso  o  en  el  lugar  preciso  donde, posterior a Ã©l la probabilidad de re contaminaciÃ³n se reduce. Debe asegurarse de mantener activa la sustancia desinfectante durante la operaciÃ³n del proceso productivo.', 10, 3, 2),
(131, 2, 24, NULL, '131', 'Â¿Se evita el contacto directo del agua contaminada sin tratar con el producto vegetal o superficies de contacto?', 'Se debe  evitar el  contacto directo de aguas contaminadas con el producto de origen  agrÃ­cola o superficies de  contacto.', 10, 4, 2),
(132, 2, 24, NULL, '132', 'Â¿Las fuentes de agua (depÃ³sitos, ollas, pilas, tinacos, aljibes, pozos, etc.) estÃ¡n protegidas de manera tal que se evite la entrada de animales domÃ©sticos y silvestres, asÃ­ como la profundidad del pozo cumple con los requisitos definidos en la NOM-003-NCA-1996?', 'Las fuentes de agua (depÃ³sitos, ollas, pilas, tinacos, aljibes, pozos, etc.) deben estar protegidas de manera tal que se evite la entrada de animales domÃ©sticos y/o silvestres, escurrimientos o brisa de sustancias quÃ­micas naturales o aplicadas intencionalmente.\r\nEl pozo profundo debe cumplir con los requisitos definidos en la NOM-003-CNA-1996.', 10, 5, 2),
(133, 2, 24, NULL, '133', 'Â¿Se aplica un programa de higiene a los depÃ³sitos generales y particulares de agua de la unidad de empaque y Ã©ste es documentado a travÃ©s de un procedimiento y registros que demuestren su cumplimiento, asÃ­ como asegurarse que las lÃ­neas de conducciÃ³n, depÃ³sitos, y fuentes de agua no presenten fugas, derrame de sustancias quÃ­micas (aceite)?', 'Debe aplicarse un programa de higiene a los depÃ³sitos generales y particulares de agua de la Unidad Empaque. Este debe ser documentado a travÃ©s de un procedimiento y registros que demuestren su cumplimiento.\r\nDebe asegurarse que las lÃ­neas de conducciÃ³n, depÃ³sitos, y fuentes de agua no presenten fugas, derrame de sustancias quÃ­micas (aceite).', 10, 6, 2),
(134, 2, 24, NULL, '134', 'Â¿Se tiene una distancia mÃ­nima suficiente, que haya sido definida en funciÃ³n de la pendiente con la finalidad de evitar que un posible contaminante  se introduzca por derrame, filtraciÃ³n, percolaciÃ³n al agua?', 'Debe asegurase una distancia mÃ­nima suficiente la cual serÃ¡ definida en funciÃ³n de la pendiente con la finalidad de evitar que un posible contaminante se introduzca por derrame, filtraciÃ³n, percolaciÃ³n, etc., al agua para estos fines.', 10, 7, 2),
(135, 2, 25, 358, '135', 'Â¿Todos los productos quÃ­micos se han almacenado en su empaque original, conservando intactas las etiquetas?', 'Todos los productos quÃ­micos deben estar almacenados en sus envases o empaques originales, conservando intactas las etiquetas.', 10, 1, 2),
(136, 2, 25, 349, '136', 'Â¿Se garantiza que los residuos de Ã©stos agentes queden en una superficie susceptible de entrar en contacto con los productos y son eliminados mediante un enjuague minucioso con agua?', 'Debe asegurarse que el agua utilizada como solvente para la preparaciÃ³n de sustancias desinfectantes no exceda los lÃ­mites mÃ¡ximos permisibles de sustancias quÃ­micas previstas en la NOM-127-SSA1-1994.', 10, 1, 2),
(137, 2, 25, 349, '137', 'Â¿Se preparan y aplican segÃºn las indicaciones del fabricante?', 'Los desinfectantes se deben preparar y aplicar segÃºn las indicaciones del fabricante.', 10, 2, 2),
(138, 2, 25, 350, '138', 'Â¿En el caso de utilizar aire antes o despuÃ©s de aplicar el recubrimiento o para cualquier otro  fin,  se  evita  que Ã©ste  provenga de espacios o  corrientes con  alta  contaminaciÃ³n ambiental y se toman medidas que reduzcan o eliminen la contaminaciÃ³n que pudiera contener?', 'En el caso de utilizar aire antes o despuÃ©s de aplicar el recubrimiento o para cualquier otro  fin,  se debe evitar  que Ã©ste  provenga de espacios o  corrientes con  alta  contaminaciÃ³n ambiental y se toman medidas que reduzcan o eliminen la contaminaciÃ³n que pudiera contener.', 10, 1, 2),
(139, 2, 25, 350, '139', 'Â¿Se evita el uso de productos caducos para tratamiento de los productos y en caso de que Ã©stos existan, elabora un inventario, almacenan en lugar especÃ­fico para este fin y se envÃ­an a un centro de destrucciÃ³n que la autoridad competente en el tema que indique?', 'Evitar el uso de productos caducos para tratamiento de los productos y en los casos donde estos existan deberÃ¡ elaborarse un inventario y almacenarse en lugar especÃ­fico para este fin. Los productos caducos deben ser enviados a centro de destrucciÃ³n que la autoridad competente o el Ã³rgano rector en el tema indique.', 10, 2, 2),
(140, 2, 25, 350, '140', 'Â¿Se realiza tratamiento tÃ©rmico al producto?', 'Realizar tratamiento tÃ©rmico al producto\r\n', 10, 3, 2),
(141, 2, 25, 351, '141', 'Â¿En  el  almacÃ©n  de  quÃ­micos  se  evita  colocar  lÃ­quidos  en  anaqueles  sobre  polvos,  los productos alcalinos con los Ã¡cidos y productos Ã¡cidos con soluciones de hipoclorito?', 'Debe evitar almacenar lÃ­quidos en anaqueles sobre polvos, los productos alcalinos con los Ã¡cidos y productos Ã¡cidos con soluciones de hipoclorito.', 10, 1, 2),
(142, 2, 25, 351, '142', 'Â¿Se han colocado seÃ±alamientos  grÃ¡ficos que indiquen prohibiciÃ³n de fumar y beber en el Ã¡rea de almacÃ©n, asÃ­ como la prohibiciÃ³n del ingreso a personas no autorizadas?', 'Debe colocar seÃ±alamientos grÃ¡ficos que indiquen prohibiciÃ³n de fumar y beber en el almacÃ©n, asÃ­ como la prohibiciÃ³n del ingreso de menores de edad y mujeres embarazadas.', 10, 2, 2),
(143, 2, 25, 351, '143', 'Â¿Los envases en los que se guardan las soluciones de detergentes o desinfectantes, preparadas, estÃ¡n rotulados claramente y  se almacenan en un lugar separado?', 'Todos los productos quÃ­micos deben estar almacenados en sus envases o empaques originales, conservando intactas las etiquetas. Todos los productos quÃ­micos deben aplicarse siguiendo las indicaciones de la etiqueta original pegada, adherida o impresa en el envase.', 10, 3, 2),
(144, 2, 25, 351, '144', 'Â¿Se  ha  designado  un  Ã¡rea  especÃ­fica  para  preparar  las  soluciones  de  detergentes, desinfectantes?', 'La empresa debe asignar un espacio para la preparaciÃ³n de mezclas de productos quÃ­micos.', 10, 4, 2),
(145, 2, 25, 352, '145', 'Â¿Se  ha  realizado  la  entrega  de  un  instructivo  que  indique  las  acciones  y  precauciones mÃ­nimas que el trabajador debe seguir durante el uso y manejo confiable de agroquÃ­micos y se ha generado evidencia documental de esta acciÃ³n?', 'Debe entregar un instructivo que indique las acciones y precauciones mÃ­nimas que el trabajador debe seguir durante el uso y manejo de sustancias quÃ­micas. Debe generar evidencia documental de esta acciÃ³n. El responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n debe asegurarse que todos los trabajadores   utilizan   los   Equipos   de   ProtecciÃ³n durante la aplicaciÃ³n y preparaciÃ³n de sustancias de quÃ­micas. Debe generar una evidencia documental o visual de esta acciÃ³n.', 5, 1, 2),
(146, 2, 25, 352, '146', 'Â¿Los trabajadores utilizan equipos de protecciÃ³n personal en buen estado, durante la preparaciÃ³n, aplicaciÃ³n y almacenamiento de sustancias quÃ­micas, que cumpla con las indicaciones de la etiqueta del (los) producto(s) empleados?', 'Los trabajadores deben utilizar equipos de protecciÃ³n durante la preparaciÃ³n, aplicaciÃ³n y almacenamiento de sustancias quÃ­micas.  El equipo de aplicaciÃ³n a utilizar serÃ¡ el indicado en la etiqueta del (los) producto(s).', 10, 2, 2),
(147, 2, 25, 352, '147', 'Â¿El almacÃ©n de quÃ­micos permanece siempre cerrado y el responsable de inocuidad o la persona designada como responsable del mismo, es la Ãºnica autorizada para la apertura y extracciÃ³n de productos?', 'El almacÃ©n de sustancias quÃ­micas, debe permanecer siempre cerrado y el responsable en Sistemas de ReducciÃ³n de Riesgos de ContaminaciÃ³n o la persona que Ã©ste designe como responsable del mismo, serÃ¡ la Ãºnica persona autorizada para la apertura y extracciÃ³n de productos agroquÃ­micos.', 10, 3, 2),
(148, 2, 26, NULL, '148', 'Â¿Se cumple con lo dispuesto en la NOM-251-SSA1-2009 en lo referente a diseÃ±o y construcciÃ³n, higiene y control de plagas?', 'DeberÃ¡n cumplir con lo dispuesto en la NOM-251-SSA1-2009,  en  lo  referente  a  diseÃ±o  y construcciÃ³n, higiene y control de plagas.', 10, 1, 2),
(149, 2, 26, NULL, '149', 'Â¿Los productos agrÃ­colas empacados cumplen con el intervalo de seguridad entre el corte del producto y la Ãºltima aspersiÃ³n de agroquÃ­micos?', 'Los productos agrÃ­colas empacados deberÃ¡n cumplir con lo siguiente:\r\nA) Asegurarse que cumplieron con el Intervalo de Seguridad entre el corte del producto y la Ãºltima aspersiÃ³n de agroquÃ­micos.', 5, 1, 2),
(150, 2, 26, NULL, '150', 'Â¿Se identifican las unidades productivas que le abastecen de productos de origen vegetal?', 'B) Identifique las Unidades Productivas que le abastecen de productos de origen agrÃ­cola.', 10, 3, 2),
(151, 2, 26, NULL, '151', 'Â¿Se  evita  empacar  productos  que  observen  la  presencia  de  materiales  ajenos  a  su composiciÃ³n natural (residuos de agroquÃ­micos, materia fecal, tierra, etc.) y son destruidos fuera de la unidad de empaque?', 'C) No deben empacarse productos que observen la presencia de materiales ajenos a su composiciÃ³n natural (residuos de agroquÃ­micos, materia fecal, tierra, etc.). Estos deben ser destruidos fuera de la unidad de empaque.', 10, 4, 2),
(152, 2, 26, NULL, '152', 'Â¿Se aplican medidas preventivas que eviten que el producto entre en contacto directo o indirecto con sustancias, materiales y superficies que lo puedan contaminar?', 'D) Aplicar las medidas preventivas que eviten que el producto entre en contacto directo o indirecto con sustancias, materiales y superficies que lo puedan contaminar.', 5, 5, 2),
(153, 2, 26, NULL, '153', 'Â¿Se evita la aplicaciÃ³n de tratamientos quÃ­micos durante el empacado de productos?', 'E) Debe  evitarse  la  aplicaciÃ³n  de  tratamientos  quÃ­micos durante  el  empacado  de  productos.  AdemÃ¡s  de  estar autorizados por la autoridad nacional competente en el tema debe asegurase que se cumpliÃ³ con el periodo de reentrada  especificado  para  el  producto  utilizado  para reiniciar con el empaque.', 10, 6, 2),
(154, 2, 26, NULL, '154', 'Â¿Se  eliminan  diariamente  residuos  de  productos  vegetales,  materiales  de  empaque, embalaje y otros que puedan atraer la presencia de plagas?', 'F) Eliminar  diariamente  residuos  de  productos  de  origen agrÃ­cola, materiales de empaque, embalaje y otros que puedan atraer la presencia de estos.', 10, 7, 2),
(155, 2, 26, NULL, '155', 'Â¿Se mantiene protegido el material de empacado y embalaje con cubiertas plÃ¡sticas y solo se mantiene descubierto el material que se utilizara durante el dÃ­a?', 'G) Mantener protegido el material de empaque y embalaje con cubiertas plÃ¡sticas. SÃ³lo se debe mantener solamente el material que serÃ¡ utilizado durante el dÃ­a.', 10, 8, 2),
(156, 2, 223, NULL, '156', 'Â¿El transporte destinado al producto, se utiliza Ãºnicamente con este fin?', 'Todos los vehÃ­culos destinados para el transporte de productos de origen agrÃ­cola deben cumplir con lo siguiente:     \r\nA) El equipo de transporte destinado al producto no debe ser utilizado con otro fin.', 10, 1, 2),
(157, 2, 223, NULL, '157', 'Â¿Las  plataformas o  contenedores son  de  materiales no  absorbentes y  de  fÃ¡cil  lavado  y desinfecciÃ³n?', 'B) Las plataformas o contenedores deben ser de materiales no absorbentes y de fÃ¡cil lavado y desinfecciÃ³n.', 10, 2, 2),
(158, 2, 223, NULL, '158', 'Â¿Las plataformas o contenedores estÃ¡n diseÃ±ados de tal forma que se protege el producto, no debe contener aberturas, daÃ±os a la plataforma, lonas o cubiertas de protecciÃ³n?', 'C) Las plataformas o contenedores deben estar diseÃ±ados de tal forma que se proteja el producto con malla sombra, lonas o transporte cerrado (caja refrigerada o caja seca).\r\nD) No debe contener aberturas, daÃ±os a la plataforma, lonas o cubiertas de protecciÃ³n, durante la cosecha y/o transporte de los productos agrÃ­colas.', 10, 3, 2),
(159, 2, 223, NULL, '159', 'Â¿Se aplica un programa de higiene (lavado y desinfecciÃ³n) para todos los vehÃ­culos previo a su utilizaciÃ³n y la higiene de estos se lleva a cabo fuera de la unidad productiva o de empaque?', 'Se debe aplicar un programa de higiene (lavado y desinfecciÃ³n) para todos los vehÃ­culos previo a su uso.', 10, 4, 2),
(160, 2, 223, NULL, '160', 'Â¿La higiene de los vehÃ­culos, se lleva a cabo fuera de la unidad productiva o empaque?', 'La higiene de los vehÃ­culos debe ocurrir fuera de la Unidad Productiva o empaque; cuando sea necesario  utilizar  un  espacio  dentro  de  Ã©sta  para dicha funciÃ³n, se deberÃ¡ realizar fuera del Ã¡rea activa de producciÃ³n, empaque, fuentes de agua, cosecha u otras zonas donde pueda representar un riesgo de contaminaciÃ³n.', 10, 5, 2),
(161, 2, 223, NULL, '161', 'Â¿Se evita que los vehÃ­culos utilizados observen fugas de combustibles, lubricantes u otras sustancias que representen un riesgo de contaminaciÃ³n a los productos?', 'Debe evitar que los vehÃ­culos utilizados observen fugas de combustibles, lubricantes u otras sustancias que representen un riesgo de contaminaciÃ³n a los productos. Evite el uso de transporte con estas caracterÃ­sticas.', 10, 6, 2),
(162, 2, 223, NULL, '162', 'Â¿El personal responsable del transporte y los cargadores, estÃ¡ capacitados sobre las prÃ¡cticas mÃ­nimas de seguridad e higiene que deben cumplirse durante el transporte del producto?', 'El personal responsable del transporte y os cargadores deben estar capacitados sobre las prÃ¡cticas mÃ­nimas de seguridad e higiene que deben cumplirse  durante   el   transporte   del   producto   y generar los registros suficientes que permitan corroborar el cumplimiento de estas acciones.', 5, 7, 2);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `modulos_diagnosticos`
--

CREATE TABLE `modulos_diagnosticos` (
  `id_modulo` int(11) NOT NULL AUTO_INCREMENT,
  `numModulo` varchar(15) DEFAULT NULL,
  `nomModulo` varchar(100) DEFAULT NULL,
  `id_tipoDiag` int(11) DEFAULT NULL,
  `orden` int(11) NOT NULL,
  `id_version` int(11) NOT NULL,
  PRIMARY KEY (`id_modulo`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=224 ;

--
-- Volcado de datos para la tabla `modulos_diagnosticos`
--

INSERT INTO `modulos_diagnosticos` (`id_modulo`, `numModulo`, `nomModulo`, `id_tipoDiag`, `orden`, `id_version`) VALUES
(17, '1', 'Registro', 2, 1, 2),
(18, '2', 'Módulo de Infraestructura Productiva', 2, 2, 2),
(19, '3', 'Módulo de Higiene', 2, 3, 2),
(20, '5', 'Capacitación y Desarrollo de Habilidades', 2, 5, 2),
(21, '6', 'Módulo de Evaluaciones Internas', 2, 6, 2),
(22, '7', 'Módulo de Validación de Procedimientos', 2, 7, 2),
(23, '8', 'Trazabilidad', 2, 8, 2),
(24, '9', 'Módulo de Manejo de Agua', 2, 9, 2),
(25, '10', 'Manejo de Sustancias Químicas', 2, 10, 2),
(26, '11', 'Empacado', 2, 11, 2),
(222, '4', 'Módulo de Manejo de Fauna Doméstica y Silvestre', 2, 4, 2),
(223, '12', 'Transporte', 2, 12, 2);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
